name: Docker Build Only (No Push)

on:

    pull_request:
        branches:
            - main
            - main-upstream
            - dev
            - release/*
            - feat/*

    push:
        branches:
            - main
            - main-upstream
            - dev
            - release/*
            - feat/*

    # Allow manual triggering with custom parameters
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to build from'
                required: true
                default: 'main'
                type: string

            dockerfile:
                description: 'Dockerfile to use'
                required: false
                default: 'Dockerfile.multi'
                type: string

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: api-build
            file: Dockerfile.multi
            image_name: librechat-dev-api
          - target: node
            file: Dockerfile
            image_name: librechat-dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          # Use the specified branch from manual input or main for auto runs
          ref: ${{ github.event.inputs.branch || 'main' }}

      # Set up Docker Buildx with the same version used in upstream workflow
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Prepare environment variables needed for the build
      - name: Prepare environment
        run: |
          cp .env.example .env
      
      # Skip local package verification to match upstream behavior
      # This avoids TypeScript errors that only appear in GitHub Actions environment

      - name: Build Docker image (without push)
        uses: docker/build-push-action@v5
        with:
          context: .
          # Use specified Dockerfile from matrix
          file: ${{ matrix.file }}
          # Use target from matrix
          target: ${{ matrix.target }}
          push: false
          # Add build cache for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Output built image to local Docker engine
          load: true
          tags: librechat:local-build