name: Docker Build Only

on:

    pull_request:
        branches:
            - main
            - main-upstream
            - dev
            - release/*
            - feat/*

    push:
        branches:
            - main
            - main-upstream
            - dev
            - release/*
            - feat/*

    # Allow manual triggering with custom parameters
    workflow_dispatch:
      inputs:
        branch:
          description: 'Branch to build from'
          required: true
          default: 'main'
          type: string
        
        ref:
          description: 'Git ref to checkout (branch, tag, or SHA)'
          required: false
          default: ''
          type: string
          
        dockerfile:
          description: 'Dockerfile to use'
          required: false
          default: 'Dockerfile.multi'
          type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: api-build
            file: Dockerfile.multi
            image_name: librechat-api
          - target: node
            file: Dockerfile
            image_name: librechat

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up QEMU
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Prepare the environment
      - name: Prepare environment
        run: |
          cp .env.example .env

      # Build and push Docker images for each target
      - name: Build images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          push: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
          platforms: linux/amd64,linux/arm64
          target: ${{ matrix.target }}
