name: Docker Build Only (Modified)

on:
    pull_request:
        branches:
            - main
            - main-upstream
            - dev
            - release/*
            - feat/*

    push:
        branches:
            - main
            - main-upstream
            - dev
            - release/*
            - feat/*

    # Allow manual triggering with custom parameters
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to build from'
                required: true
                default: 'main'
                type: string

            dockerfile:
                description: 'Dockerfile to use'
                required: false
                default: 'Dockerfile.multi'
                type: string

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          # Use the specified branch from manual input or main for auto runs
          ref: ${{ github.event.inputs.branch || 'main' }}

      # Pre-build setup to verify environment
      - name: Verify npm environment
        run: |
          npm --version
          node --version
          npm config set fetch-retry-maxtimeout 600000
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 15000

      - name: Verify MCP package builds locally
        run: |
          npm ci
          cd packages/data-provider && npm run build
          cd ../mcp && npm run build
          cd ../data-schemas && npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          # Create a new builder instance that closely matches local environment
          driver-opts: |
            image=moby/buildkit:master

      - name: Build Docker image (without push)
        uses: docker/build-push-action@v4
        with:
          context: .
          # Use specified Dockerfile or default
          file: ${{ github.event.inputs.dockerfile || 'Dockerfile.multi' }}
          push: false
          # Add platform specification like in local build
          platforms: linux/amd64
          # More detailed output
          progress: plain
          # Add build cache for faster builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Output built image to local Docker engine
          load: true
          tags: librechat:local-build