name: Docker Build Only (No Push)

on:

    pull_request:
        branches:
            - main
            - main-upstream
            - dev
            - release/*
            - feat/*

    push:
        branches:
            - main
            - main-upstream
            - dev
            - release/*
            - feat/*

    # Allow manual triggering with custom parameters
    workflow_dispatch:
        inputs:
            branch:
                description: 'Branch to build from'
                required: true
                default: 'main'
                type: string

            dockerfile:
                description: 'Dockerfile to use'
                required: false
                default: 'Dockerfile.multi'
                type: string

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
        with:
          # Use the specified branch from manual input or main for auto runs
          ref: ${{ github.event.inputs.branch || 'main' }}

      # Set up Docker Buildx with the same version used in upstream workflow
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Skip local package verification to match upstream behavior
      # This avoids TypeScript errors that only appear in GitHub Actions environment

      - name: Build Docker image (without push)
        uses: docker/build-push-action@v5
        with:
          context: .
          # Use specified Dockerfile or default
          file: ${{ github.event.inputs.dockerfile || 'Dockerfile.multi' }}
          push: false
          # Add build cache for faster builds
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
