name: Mirror Upstream

on:
  # Runs once a day at 07:00 UTC
  schedule:
    - cron: '0 7 * * *'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main-upstream
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/danny-avila/LibreChat.git
          git fetch upstream

      - name: Check if upstream has changes
        id: check_changes
        run: |
          # Compare local main-upstream with upstream/main to see if new commits exist
          LOCAL=$(git rev-parse main-upstream)
          REMOTE=$(git rev-parse upstream/main)
          if [ "$LOCAL" = "$REMOTE" ]; then
            echo "::set-output name=has_changes::false"
          else
            echo "::set-output name=has_changes::true"
          fi

      - name: Mirror upstream changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # Configure Git
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          # Reset local branch to match upstream exactly
          git checkout main-upstream
          git fetch upstream
          git reset --hard upstream/main

          # Force-push local mirror branch to origin
          git push --force origin main-upstream
