name: JM - Upstream Sync

on:
  # Run on a daily schedule
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Branch to run the sync from (default: the branch where the workflow is defined)'
        required: false
        default: ''
      target_branch:
        description: 'Branch to push the synced content to'
        required: false
        default: 'main-upstream'

# Add permissions required for workflow file updates
permissions:
  contents: write
  workflows: write

jobs:
  upstream-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Determine target branch
        id: set-branch
        run: |
          TARGET_BRANCH="${{ github.event.inputs.target_branch }}"
          if [ -z "$TARGET_BRANCH" ]; then
            TARGET_BRANCH="main-upstream"
          fi
          echo "target_branch=$TARGET_BRANCH" >> $GITHUB_OUTPUT
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.set-branch.outputs.target_branch }}
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Fetch upstream and force push
        run: |
          git remote add upstream https://github.com/danny-avila/LibreChat.git
          git fetch upstream main
          git reset --hard upstream/main
          git push --force origin ${{ steps.set-branch.outputs.target_branch }}
